# Generated by Django 5.2.7 on 2025-11-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', '创建'), ('UPDATE', '更新'), ('DELETE', '删除'), ('LOGIN', '登录'), ('LOGOUT', '退出'), ('LOGIN_FAILED', '登录失败')], help_text='操作类型', max_length=20, verbose_name='操作类型'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='模型名称'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='record_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='记录ID'),
        ),
    ]
