# Generated by Django 5.2.7 on 2025-11-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perm', '0003_alter_permission_name_alter_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='is_system',
            field=models.BooleanField(default=False, verbose_name='是否为系统权限'),
        ),
    ]
