# Generated by Django 5.2.7 on 2025-11-08 13:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LdapConfig',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('server_uri', models.CharField(max_length=255, verbose_name='服务器地址')),
                ('base_dn', models.CharField(max_length=255, verbose_name='基础DN')),
                ('admin_dn', models.CharField(max_length=255, verbose_name='管理员DN')),
                ('admin_password', models.CharField(max_length=255, verbose_name='管理员密码')),
                ('user_search_filter', models.CharField(default='(objectClass=user)', max_length=255, verbose_name='用户搜索过滤器')),
                ('username_attr', models.CharField(default='sAMAccountName', max_length=100, verbose_name='用户名属性')),
                ('display_name_attr', models.CharField(default='displayName', max_length=100, verbose_name='显示名属性')),
                ('email_attr', models.CharField(default='mail', max_length=100, verbose_name='邮箱属性')),
                ('enabled', models.BooleanField(default=False, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': 'LDAP配置',
                'verbose_name_plural': 'LDAP配置',
            },
        ),
        migrations.CreateModel(
            name='SecurityConfig',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('max_login_attempts', models.IntegerField(default=5, verbose_name='最大登录尝试次数')),
                ('lockout_duration', models.IntegerField(default=60, verbose_name='锁定持续时间(分钟)')),
            ],
            options={
                'verbose_name': '安全配置',
                'verbose_name_plural': '安全配置',
            },
        ),
    ]
