# Generated by Django 5.2.7 on 2025-11-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldapauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldapconfig',
            name='ldap_type',
            field=models.CharField(choices=[('openldap', 'OpenLDAP'), ('ad', 'Active Directory')], default='ad', max_length=20, verbose_name='LDAP类型'),
        ),
    ]
