# Generated by Django 5.2.7 on 2025-11-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldapauth', '0002_ldapconfig_ldap_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ldapconfig',
            name='server_uri',
        ),
        migrations.AddField(
            model_name='ldapconfig',
            name='protocol',
            field=models.CharField(default='ldap', max_length=10, verbose_name='协议'),
        ),
        migrations.AddField(
            model_name='ldapconfig',
            name='server_host',
            field=models.CharField(default=1, max_length=255, verbose_name='服务器主机'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ldapconfig',
            name='server_port',
            field=models.IntegerField(default=389, verbose_name='服务器端口'),
        ),
    ]
