# Generated by Django 5.2.7 on 2025-11-09 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ldapauth', '0003_remove_ldapconfig_server_uri_ldapconfig_protocol_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ldapconfig',
            name='protocol',
        ),
    ]
