LOG_LEVEL: "DEBUG"

SETTINGS: {
  DEBUG: true,
  ALLOWED_HOSTS: [
    'localhost',
    '127.0.0.1:8000',
    '127.0.0.1'
  ],
  CSRF_TRUSTED_ORIGINS: [
    'https://localhost:8000',
    'http://127.0.0.1:8000',
    'http://127.0.0.1'
  ],
  CORS_ALLOWED_ORIGINS: [
    'http://127.0.0.1:8080',
    'http://localhost:8080'
  ]
}

AES_KEY: "dTDR80ClnxN93QmX"


# Token配置
AUTH: {
  "ACCESS_TOKEN_EXPIRE": 10,  # 2小时
  "REFRESH_TOKEN_EXPIRE": 604800,  # 7天
  "JWT_SECRET": "JbzhCpYqofMDBb9A8AWte7jXiwp1FxI0TGWoq8FSI6DMrdPqtt",
  "JWT_ALGORITHM": "HS256",
}

MIDDLEWARE_WHITE_LIST: {
    "/api/v1/auth/login/": ["POST"],
    "/api/v1/auth/refresh-token/": ["POST"],
    "/api/v1/demo": ["GET"]
}

MYSQL: {
  "HOST": "127.0.0.1",
  "PORT": 13306,
  "USER": "root",
  "PASSWORD": "Admin@123",
  "DB": "backend"
}

HAS_REDIS: true
REDIS: {
  "HOST": "172.17.0.1",
  "PORT": 16379,
  "PASSWORD": "123456",
  "DB": {
    "DEFAULT": 0,
    # celery
    "CELERY": 1,
    # celery broker
    "CELERY_BROKER": 2,
    # 认证
    "AUTH": 3,
  },
}