# Generated by Django 5.2.7 on 2025-11-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_ldap',
            field=models.BooleanField(default=False, verbose_name='是否为LDAP用户'),
        ),
        migrations.AddField(
            model_name='user',
            name='ldap_dn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='LDAP DN'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='密码'),
        ),
    ]
