# Generated by Django 5.2.7 on 2025-11-09 13:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_is_ldap_user_ldap_dn_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('config_key', models.CharField(max_length=100, unique=True, verbose_name='配置键')),
                ('config_value', models.TextField(verbose_name='配置值')),
                ('description', models.TextField(blank=True, null=True, verbose_name='配置描述')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
            },
        ),
    ]
